# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ResticCoverage < Formula
  desc "Audit that everything on disk is deliberately backed up, excluded, or ignored by a resticprofile setup"
  homepage "https://github.com/Miista/homebrew-restic-coverage"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.1/restic-coverage_0.1.1_darwin_amd64.tar.gz"
      sha256 "54d9f4e3fcfb1e225e16ceb99725420469fd71e0a14bcad3c96e6f6c7601b021"

      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.1/restic-coverage_0.1.1_darwin_arm64.tar.gz"
      sha256 "e184ce3b843d296818932c2b991fdacaf6f265dd0efd89f3eb8fa40944c52b14"

      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.1/restic-coverage_0.1.1_linux_amd64.tar.gz"
      sha256 "331a1174d0ba50557bd295ef10fd22c9cdd8e22eba411c2a04f9f3c94e6c5644"
      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.1/restic-coverage_0.1.1_linux_arm64.tar.gz"
      sha256 "e88323ae0a71f1a5b01b030f30d8978086305939608f31f57573159689ae5395"
      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
  end

  test do
    assert_match "restic-coverage", shell_output("#{bin}/restic-coverage version")
  end
end
