# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ResticCoverage < Formula
  desc "Audit that everything on disk is deliberately backed up, excluded, or ignored by a resticprofile setup"
  homepage "https://github.com/Miista/homebrew-restic-coverage"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.0/restic-coverage_0.1.0_darwin_amd64.tar.gz"
      sha256 "d01aa1c4f64b6fb597c8b6a12764fca913b84258d95f53a124368eb12dae08b8"

      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.0/restic-coverage_0.1.0_darwin_arm64.tar.gz"
      sha256 "d8fe739d0665531cede6849b954cb6098c5d18e7b86cc478365874343e73f1c4"

      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.0/restic-coverage_0.1.0_linux_amd64.tar.gz"
      sha256 "25255dc315f84345fa86dfa6b8cc2197afce31c3dd5ebdf0d4aec5f343405a99"
      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-restic-coverage/releases/download/v0.1.0/restic-coverage_0.1.0_linux_arm64.tar.gz"
      sha256 "a6f99d41e0c5626ed910d6fa16a5323dab48d915f298d15faf4d86f8455bc34d"
      define_method(:install) do
        bin.install "restic-coverage"
      end
    end
  end

  test do
    assert_match "restic-coverage", shell_output("#{bin}/restic-coverage version")
  end
end
